'use strict';

/** @const {!Object<string, boolean>} */
Wasm2Lang.Backend.JavaCodegen.RESERVED_ = Wasm2Lang.Backend.buildReservedSet([
  'abstract',
  'assert',
  'boolean',
  'break',
  'byte',
  'case',
  'catch',
  'char',
  'class',
  'const',
  'continue',
  'default',
  'do',
  'double',
  'else',
  'enum',
  'extends',
  'false',
  'final',
  'finally',
  'float',
  'for',
  'goto',
  'if',
  'implements',
  'import',
  'instanceof',
  'int',
  'interface',
  'long',
  'native',
  'new',
  'null',
  'package',
  'private',
  'protected',
  'public',
  'return',
  'short',
  'static',
  'strictfp',
  'super',
  'switch',
  'synchronized',
  'this',
  'throw',
  'throws',
  'transient',
  'true',
  'try',
  'var',
  'void',
  'volatile',
  'while',
  '_'
]);

Wasm2Lang.Backend.registerManglerProfile('java', {
  reservedWords: Wasm2Lang.Backend.JavaCodegen.RESERVED_,
  rejectName: Wasm2Lang.Backend.buildRejectName(Wasm2Lang.Backend.JavaCodegen.RESERVED_, false),
  singleCharset: '$ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz',
  blockCharset: '$ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz0123456789',
  caseInsensitive: false
});
