'use strict';

// ---------------------------------------------------------------------------
// Reserved words and mangler profile.
// ---------------------------------------------------------------------------

/** @const {!Object<string, boolean>} */
Wasm2Lang.Backend.Php64Codegen.RESERVED_ = Wasm2Lang.Backend.buildReservedSet([
  'abstract',
  'and',
  'array',
  'as',
  'break',
  'callable',
  'case',
  'catch',
  'class',
  'clone',
  'const',
  'continue',
  'declare',
  'default',
  'die',
  'do',
  'echo',
  'else',
  'elseif',
  'empty',
  'enddeclare',
  'endfor',
  'endforeach',
  'endif',
  'endswitch',
  'endwhile',
  'eval',
  'exit',
  'extends',
  'false',
  'final',
  'finally',
  'fn',
  'for',
  'foreach',
  'function',
  'global',
  'goto',
  'if',
  'implements',
  'include',
  'include_once',
  'instanceof',
  'insteadof',
  'interface',
  'isset',
  'list',
  'match',
  'namespace',
  'new',
  'null',
  'or',
  'print',
  'private',
  'protected',
  'public',
  'readonly',
  'require',
  'require_once',
  'return',
  'static',
  'switch',
  'throw',
  'trait',
  'true',
  'try',
  'unset',
  'use',
  'var',
  'while',
  'xor',
  'yield'
]);

Wasm2Lang.Backend.registerManglerProfile('php64', {
  reservedWords: Wasm2Lang.Backend.Php64Codegen.RESERVED_,
  rejectName: /** @param {string} name @return {boolean} */ function (name) {
    var /** @const {number} */ ch = name.charCodeAt(0);
    return (48 <= ch && ch <= 57) || !!Wasm2Lang.Backend.Php64Codegen.RESERVED_[name.toLowerCase()];
  },
  singleCharset: 'abcdefghijklmnopqrstuvwxyz_',
  blockCharset: 'abcdefghijklmnopqrstuvwxyz_0123456789',
  caseInsensitive: true
});
