'use strict';

// ---------------------------------------------------------------------------
// Reserved-word lexicon shared by the JavaScript-family backends (asm.js +
// modern JavaScript).  Both targets must avoid colliding with the union of
// all ECMAScript reserved/strict/future words; the modern-JS profile layers
// a few host-globals (BigInt, Math, typed-array constructors) on top because
// it references them by name in emitted code.
// ---------------------------------------------------------------------------

/** @const {!Array<string>} */
Wasm2Lang.Backend.JsCommonCodegen.JS_KEYWORDS_ = [
  'abstract',
  'arguments',
  'await',
  'boolean',
  'break',
  'byte',
  'case',
  'catch',
  'char',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'double',
  'else',
  'enum',
  'eval',
  'export',
  'extends',
  'false',
  'final',
  'finally',
  'float',
  'for',
  'function',
  'goto',
  'if',
  'implements',
  'import',
  'in',
  'instanceof',
  'int',
  'interface',
  'let',
  'long',
  'native',
  'new',
  'null',
  'of',
  'package',
  'private',
  'protected',
  'public',
  'return',
  'short',
  'static',
  'super',
  'switch',
  'synchronized',
  'this',
  'throw',
  'throws',
  'transient',
  'true',
  'try',
  'typeof',
  'undefined',
  'var',
  'void',
  'volatile',
  'while',
  'with',
  'yield',
  'NaN',
  'Infinity'
];
